### ISSUE TITLE
Allow default keyboard

### ISSUE THREAD

**Issue by cemolcay** [Serheo/SHSPhoneComponent#11]
hi, thanks for great library !
i subclassed my custom text field with SHSPhoneTextField instead of UITextField for be able to use formatter.
But now my textfields only accept numbers since your library somehow trims characters other than numbers.
how can i fix this and support every character in the keyboard like regular text fields ?

**Comment by Serheo** [comment]
Hi, Thank you for the words!
I'll try to improve the library in a week or two.

**Comment by cemolcay** [comment]
cool, thanks :+1:

**Comment by Serheo** [comment]
It was not so easy as I imagine, but now you can find example (Example_iOS7+ folder) in 'beta' branch.
You can use SHSTextableTextField class with any keyboard your want. It accept all symbols that match '\w' regexp (can be modified in SHSTextFormatter.m isValuableChar method).
Unfortunately it's not ready for master release now, but I believe It will fit you requirements.
Hope it helps. Sorry for delay.

**Comment by cemolcay** [comment]
that was just what i needed, many thanks to you ! 🎉
