### ISSUE TITLE
Version 2.2 in CocoaPods

### ISSUE THREAD

**Issue by brightsider** [Serheo/SHSPhoneComponent#12]
Hello! I can't update the library via CocoaPods to version 2.2. I need to use pod 'SHSPhoneComponent', :git => 'https://github.com/Serheo/SHSPhoneComponent.git' for updating.
When use pod outdate console log show:
- SHSPhoneComponent 2.2 -> 2.2 (latest version 2.15)

**Comment by Serheo** [comment]
updated.
