### ISSUE TITLE
Reactive Cocoa not working for SHSPhoneComponent

### ISSUE THREAD

**Issue by petrovi4** [Serheo/SHSPhoneComponent#13]
After this code

RAC(self.phoneField, text) = RACObserve(user, phone);
RAC(user, phone) = self.phoneField.rac_newTextChannel;

user.phone always empty.

**Comment by ShuNegus** [comment]
@petrovi4 
I don't know actual or not :) But You can observe text by keyPath. Example:
`phoneTextField.rx.observe(String.self, "text").bind(to: output.phoneVariable).disposed(by: disposeBag)`
