### ISSUE TITLE
Show mask?

### ISSUE THREAD

**Issue by ADevelopStudio** [Serheo/SHSPhoneComponent#14]
Hi,
Is any way to show user input mask?
Something like: +1(___) __ __ __ 
or like in attachment 

<img width="140" alt="sample-screenshot" src="https://cloud.githubusercontent.com/assets/5238454/14775358/f401b61e-0b01-11e6-9c88-4b05be38020e.png">

**Comment by Serheo** [comment]
Hi! Sorry, placeholder doesn't supported.

**Comment by ADevelopStudio** [comment]
Ok, no worries
