### ISSUE TITLE
iOS 11 UITextField Content Type (Telephone Number)

### ISSUE THREAD

**Issue by ryancoyne** [Serheo/SHSPhoneComponent#18]
The new Telephone Number content type for UITextFields are incompatible using the users suggested phone number when using a format (i.e. +1 (###) - ### ####).  When the user presses their suggested phone number, it enters a blank string.

**Comment by Serheo** [comment]
I'll take a look. Thank you!

**Comment by ryancoyne** [comment]
Awesome.  Thank you.  Let me know if you have any other questions about it

**Comment by Serheo** [comment]
I'm not proud of the solution but looks like I have one.
Do you have predictions only if the textfield is empty? 
If yes - please try a solution from branch 'fix18'. (You need to set hasPredictiveInput parameter to YES this time)
if it works I'll submit a Pod.

**Comment by ryancoyne** [comment]
Awesome - it worked.
And yes, I only get predictions when the textfield is empty.

Thank you for fixing that!

Ryan Coyne

*Mobile Development Engineer*
*Co-founder of ClearCodeX, Inc.*
*University of Maryland Eastern Shore*
*Computer Engineering*
*Skype*: ryancoyne_
*Office:*
1342 Florida Ave NW
Washington, DC 20009
Second Floor

On September 30, 2017 at 12:09:28 AM, Serheo (notifications@github.com)
wrote:

I'm not proud of the solution but looks like I have one.
Do you have predictions only if the textfield is empty?
If yes - please try a solution from branch 'fix18'. (You need to set
hasPredictiveInput parameter to YES this time)
if it works I'll submit a Pod.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Serheo/SHSPhoneComponent/issues/18#issuecomment-333281786>,
or mute the thread

**Comment by ryancoyne** [comment]
Awesome - it worked.
And yes, I only get predictions when the textfield is empty.

Thank you for fixing that!
